name: .NET Core Desktop Build and Release

on:
  push:
    branches:
      - 'Pre-Master'

env:
  Solution_Name: vrcosc-magicchatbox.sln
  Project_Path: vrcosc-magicchatbox\vrcosc_magicchatbox.csproj

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore -p:Platform="Any CPU"

    - name: Extract Version from csproj
      id: get_version
      run: |
        $csproj = "vrcosc-magicchatbox\MagicChatbox.csproj"
        $pattern = '<Version>(.*)<\/Version>'
        $content = Get-Content $csproj -Raw
        $match = [regex]::Match($content, $pattern)
        if ($match.Success -and $match.Groups.Count -gt 1) {
          $version = $match.Groups[1].Value
          echo "VERSION=$version" | Out-File -Append -Encoding utf8 $Env:GITHUB_ENV
          echo "::set-output name=VERSION::$version"
        } else {
          echo "Error: Version not found in csproj file."
          exit 1
        }
      shell: pwsh
      env:
        Solution_Name: vrcosc-magicchatbox.sln
        Project_Path: vrcosc-magicchatbox\MagicChatbox.csproj

    - name: Create Zip File
      run: |
        Compress-Archive -Path vrcosc-magicchatbox/bin/Release/net6.0-windows10.0.22000.0/* -DestinationPath "MagicChatbox-${{ steps.get_version.outputs.VERSION }}.zip"

    - name: Upload and Scan with VirusTotal
      id: virustotal_scan
      run: |
        $file_path = "./MagicChatbox-${{ steps.get_version.outputs.VERSION }}.zip"
        $api_key = "${{ secrets.VIRUSTOTAL_API_KEY }}"
        
        $response = Invoke-RestMethod -Uri "https://www.virustotal.com/api/v3/files" -Method Post -Headers @{
          "x-apikey" = $api_key
        } -Form @{
          "file" = Get-Item $file_path
        }
        
        $scan_id = $response.data.id
        echo "::set-output name=SCAN_ID::$scan_id"

    - name: Get VirusTotal Scan Report
      id: virustotal_report
      run: |
        $api_key = "${{ secrets.VIRUSTOTAL_API_KEY }}"
        $scan_id = "${{ steps.virustotal_scan.outputs.SCAN_ID }}"
        
        $response = Invoke-RestMethod -Uri "https://www.virustotal.com/api/v3/analyses/$scan_id" -Headers @{
          "x-apikey" = $api_key
        }
        
        $report_url = "https://www.virustotal.com/gui/file/$($response.meta.file_info.sha256)/detection"
        echo "::set-output name=REPORT_URL::$report_url"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: true
        body: |
          # MagicChatbox Pre-v${{ steps.get_version.outputs.VERSION }} ![GitHub release (latest by date)](https://img.shields.io/github/downloads/BoiHanny/vrcosc-magicchatbox/v${{ steps.get_version.outputs.VERSION }}/total?color=%23AB3BFF&label=Version%20downloads&logo=%20&style=plastic)
          <!-- BEGIN LATEST DOWNLOAD BUTTON -->
          # Download the latest version and update in the app.
          ### Manual Download and Installation
          1. Download the .zip
          2. Make sure you have [.NET 6](https://dotnet.microsoft.com/en-us/download) installed.
          3. Right-click and choose the option 'extract all'.
          4. By default it will create a new folder in your download folder (you can also extract the content to other locations).
          5. When extracted, the folder will open.
          6. Run the file 'MagicChatbox.exe'.

          [![Download zip](https://custom-icon-badges.herokuapp.com/badge/-Download-%23512BD4?style=for-the-badge&logo=download&logoColor=white "Download")](https://github.com/BoiHanny/vrcosc-magicchatbox/releases/download/v${{ steps.get_version.outputs.VERSION }}/MagicChatbox-${{ steps.get_version.outputs.VERSION }}.zip)
          [![Scan at VirusTotal](https://custom-icon-badges.herokuapp.com/badge/-Scan%20at%20VirusTotal-blue?style=for-the-badge&logo=virustotal&logoColor=white "virustotal")](https://www.virustotal.com/gui/file/${{ steps.virustotal_report.outputs.REPORT_URL }}/detection)

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MagicChatbox-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: MagicChatbox-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
